server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gritter?useSSl=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345

log4j2:
  contextSelector: org.apache.logging.log4j.core.async.AsyncLoggerContextSelector